### ISSUE TITLE
请问有遇到文件保存的回调的status都是7或者3吗？

### ISSUE THREAD

**Issue by weiboboCN** [xbeeant/oo-chinese-license#2]
请问有遇到文件保存的回调收到的消息status都是7或者3吗？没有保存成功过，请问如何查看documentserver的错误日志呢？
<img width="411" alt="image" src="https://user-images.githubusercontent.com/23450893/174574392-f3972a0d-6436-499c-86e2-4df5cfb51d47.png">

**Comment by beeant0512** [comment]
@weiboboCN 没有遇到过
