### ISSUE TITLE
最新的7.3.0.184有bug JWT_ENABLED=false 失效, 可以再更新一下最新7.3版本吗

### ISSUE THREAD

**Issue by GGBeng1** [xbeeant/oo-chinese-license#5]
最新的7.3.0.184有bug JWT_ENABLED=false 失效, 可以再更新一下最新7.3版本吗

**Comment by beeant0512** [comment]
> 最新的7.3.0.184有bug JWT_ENABLED=false 失效, 可以再更新一下最新7.3版本吗

试试7.3.2.8
