### ISSUE TITLE
是否能帮忙出一个去除左上角logo以及关于菜单的docker镜像

### ISSUE THREAD

**Issue by yanchiuvip** [xbeeant/oo-chinese-license#9]
![G@~I_P7NDVKRMQ8L3L6PMDX](https://github.com/xbeeant/oo-chinese-license/assets/63529996/d75b0fa9-c30e-406f-8e86-b80b52241994)

**Comment by beeant0512** [comment]
see： https://api.onlyoffice.com/editors/config/editor/customization#logo
